[package]
name = "lm75_raspi"
version = "0.1.0"
authors = ["Mikko Viitamäki <mikko.viitamaki@gmail.com>"]
edition = "2018"

[dependencies]
lm75 = "0.1.1"
linux-embedded-hal = "0.3.0"
chrono = "0.4.19"
csv = "1.1.5"
serde = { version = "1", features = ["derive"] }
